// Package tailscale is Rover's local-side Tailscale integration: it inspects the
// tailnet via the `tailscale` CLI to find the Rover VM and connects to it over
// Tailscale SSH, independent of the Azure public IP.
package tailscale

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"time"
)

// Peer is the subset of `tailscale status --json` we care about.
type Peer struct {
	HostName     string   `json:"HostName"`
	DNSName      string   `json:"DNSName"`
	Online       bool     `json:"Online"`
	TailscaleIPs []string `json:"TailscaleIPs"`
}

type statusJSON struct {
	BackendState string           `json:"BackendState"`
	Peer         map[string]*Peer `json:"Peer"`
}

// Available reports whether the local `tailscale` CLI is installed.
func Available() bool {
	_, err := exec.LookPath("tailscale")
	return err == nil
}

// ErrNotInstalled is returned when the tailscale CLI is missing.
var ErrNotInstalled = fmt.Errorf("tailscale CLI not found; install it from https://tailscale.com/download and run 'tailscale up'")

// ErrNotRunning is returned when the local tailscale backend isn't connected.
var ErrNotRunning = fmt.Errorf("local Tailscale is not connected; run 'tailscale up'")

// PeerNotFoundError indicates the named host isn't in the tailnet.
type PeerNotFoundError struct{ Host string }

func (e *PeerNotFoundError) Error() string {
	return fmt.Sprintf("%q is not in your tailnet", e.Host)
}

// FindPeer returns the tailnet peer matching host (by short hostname or the
// leading label of its MagicDNS name).
func FindPeer(host string) (*Peer, error) {
	if !Available() {
		return nil, ErrNotInstalled
	}
	out, err := exec.Command("tailscale", "status", "--json").Output()
	if err != nil {
		return nil, fmt.Errorf("tailscale status: %w", err)
	}
	var st statusJSON
	if err := json.Unmarshal(out, &st); err != nil {
		return nil, fmt.Errorf("parse tailscale status: %w", err)
	}
	if st.BackendState != "Running" {
		return nil, ErrNotRunning
	}
	want := strings.ToLower(host)
	for _, p := range st.Peer {
		if strings.EqualFold(p.HostName, want) || strings.HasPrefix(strings.ToLower(p.DNSName), want+".") {
			return p, nil
		}
	}
	return nil, &PeerNotFoundError{Host: host}
}

// Target returns the best address to connect to (MagicDNS name, else IP).
func (p *Peer) Target() string {
	if p.DNSName != "" {
		return strings.TrimSuffix(p.DNSName, ".")
	}
	if len(p.TailscaleIPs) > 0 {
		return p.TailscaleIPs[0]
	}
	return p.HostName
}

// Connect opens an interactive Tailscale SSH session to user@host's peer.
func Connect(user, host string, extra ...string) error {
	if !Available() {
		return ErrNotInstalled
	}
	args := append([]string{"ssh", user + "@" + host}, extra...)
	cmd := exec.Command("tailscale", args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// GetAuthKey generates an ephemeral Tailscale auth key using Tailscale OAuth client credentials.
func GetAuthKey(clientID, clientSecret string, tags []string) (string, error) {
	// 1. Get access token via OAuth
	tokenURL := "https://api.tailscale.com/api/v2/oauth/token"
	data := url.Values{}
	data.Set("client_id", clientID)
	data.Set("client_secret", clientSecret)
	data.Set("grant_type", "client_credentials")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm(tokenURL, data)
	if err != nil {
		return "", fmt.Errorf("oauth token request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("oauth token request failed (status %d): %s", resp.StatusCode, string(body))
	}

	var tokenRes struct {
		AccessToken string `json:"access_token"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenRes); err != nil {
		return "", fmt.Errorf("decode oauth response: %w", err)
	}

	// 2. Create Auth Key
	keyURL := "https://api.tailscale.com/api/v2/tailnet/-/keys"

	type deviceCreate struct {
		Reusable      bool     `json:"reusable"`
		Ephemeral     bool     `json:"ephemeral"`
		Preauthorized bool     `json:"preauthorized"`
		Tags          []string `json:"tags"`
	}
	type keyCapabilities struct {
		Devices struct {
			Create deviceCreate `json:"create"`
		} `json:"devices"`
	}
	type createKeyPayload struct {
		Capabilities  keyCapabilities `json:"capabilities"`
		ExpirySeconds int             `json:"expirySeconds"`
		Description   string          `json:"description"`
	}

	payload := createKeyPayload{
		ExpirySeconds: 3600, // 1 hour
		Description:   "Automated key generated by Rover CLI",
	}
	payload.Capabilities.Devices.Create.Reusable = false
	payload.Capabilities.Devices.Create.Ephemeral = true
	payload.Capabilities.Devices.Create.Preauthorized = true
	payload.Capabilities.Devices.Create.Tags = tags

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal key payload: %w", err)
	}

	req, err := http.NewRequest("POST", keyURL, bytes.NewReader(payloadBytes))
	if err != nil {
		return "", fmt.Errorf("create key request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+tokenRes.AccessToken)

	keyResp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("execute create key request: %w", err)
	}
	defer func() { _ = keyResp.Body.Close() }()

	if keyResp.StatusCode != http.StatusOK && keyResp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(keyResp.Body)
		return "", fmt.Errorf("create key failed (status %d): %s", keyResp.StatusCode, string(body))
	}

	var keyRes struct {
		Key string `json:"key"`
	}
	if err := json.NewDecoder(keyResp.Body).Decode(&keyRes); err != nil {
		return "", fmt.Errorf("decode key response: %w", err)
	}

	return keyRes.Key, nil
}
